name: black-action
on: [push]
jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."

      - name: Commit changes if any files were formatted
        if: steps.action_black.outputs.is_formatted == 'true'
        env:
          PAT_TOKEN: ${{ secrets.BLACK_ACTION_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Format Python code with psf/black"
          git push https://x-access-token:${{ secrets.BLACK_ACTION_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}



