name: black-action
on: [push, pull_request]
jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."

      - name: Commit and Push changes
        if: steps.action_black.outputs.is_formatted == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am ":art: Format Python code with psf/black"
          git push origin ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.BLACK_ACTION_TOKEN }}
